angular.module('tableauUnhcrConnectorApp').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('views/about.html',
    "<div class=\"row col-md-8 center-block\"> <section class=\"main-content\"> <h3> <p>Tableau UNHCR Connector can be used to import data from he UNHCR API straight into <a href=\"http://www.tableau.com/\">Tableau</a></p> <footer class=\"site-footer\"> <span class=\"site-footer-owner\"><a href=\"https://github.com/alexeiZamyatin/tableau-unhcr-connector\">Tableau-unhcr-connector</a> is maintained by <a href=\"https://github.com/alexeiZamyatin\">alexeiZamyatin</a>.</span> <span class=\"site-footer-credits\">This page was generated by <a href=\"https://pages.github.com\">GitHub Pages</a> using the <a href=\"https://github.com/jasonlong/cayman-theme\">Cayman theme</a> by <a href=\"https://twitter.com/jasonlong\">Jason Long</a>.</span> </footer> </h3> </section> </div>"
  );


  $templateCache.put('views/unhcr-connector.html',
    "<div class=\"col-xs-12 large-bot-buffer\"> <!-- /.row --> <div class=\"row col-md-8 center-block\"> <h3 class=\"text-center\">Please select the data you would like to retrieve</h3> <div class=\"col-md-12 center-block\"> <div class=\"panel panel-default col-md-6 small-margin-bot\" data-ng-repeat=\"apiCall in vm.apiCalls\"> <div class=\"panel-body clearfix small-padding\"> <div class=\"col-xs-12\"> <div class=\"col-xs-6 form-control-static\"> <label>{{apiCall.name}}</label> </div> <div class=\"col-xs-1 pull-right form-control-static\"> <input type=\"checkbox\" data-ng-click=\"apiCall.sel = true\"> </div> <div data-ng-show=\"apiCall.params\" class=\"col-xs-5 pull-right\"> <p for=\"value\" class=\"col-xs-2 control-label form-control-static\">{{apiCall.paramName}}</p> <div class=\"col-xs-9 col-xs-offset-1 text-left\"> <input type=\"text\" class=\"form-control\" id=\"value\" data-ng-model=\"apiCall.paramValue\" required> </div> </div> </div> </div> </div> <div class=\"col-xs-12 text-right small-margin-bottom\"> <label data-ng-show=\"vm.error\" class=\"red\">{{vm.error}}</label> <button type=\"submit\" class=\"btn btn-success\" data-ng-click=\"vm.submit()\">Download Selected</button> <button type=\"submit\" class=\"btn btn-success\" data-ng-click=\"vm.submitAll()\">Download All</button> </div> </div> <!-- /.col-lg-4 --> </div> <!-- /.row --> </div>"
  );

}]);
